#!/bin/sh

# Xcode Cloud post-clone step.
#
# Secrets.swift is gitignored (it isn't in the repo), but the build depends on it.
# Regenerate it here from environment variables you set in the Xcode Cloud workflow:
#   SUPABASE_URL        e.g. https://<project>.supabase.co
#   SUPABASE_ANON_KEY   the anon/publishable key (public-by-design; RLS is the real defense)
#
# To set them: App Store Connect → Xcode Cloud → your workflow → Environment → Environment Variables.

set -e

if [ -z "$SUPABASE_URL" ] || [ -z "$SUPABASE_ANON_KEY" ]; then
  echo "❌ ci_post_clone: SUPABASE_URL and/or SUPABASE_ANON_KEY are not set."
  echo "   Set them in the Xcode Cloud workflow's Environment Variables, then re-run."
  exit 1
fi

SECRETS_PATH="$CI_PRIMARY_REPOSITORY_PATH/BumpSetCut/Core/Networking/Secrets.swift"

cat > "$SECRETS_PATH" <<EOF
// Secrets.swift — generated by ci_scripts/ci_post_clone.sh during Xcode Cloud builds.
// Local dev keeps its own gitignored copy; do not commit this file.

import Foundation

enum Secrets {
    static let supabaseURL = "$SUPABASE_URL"
    static let supabaseAnonKey = "$SUPABASE_ANON_KEY"
}
EOF

echo "✅ ci_post_clone: wrote Secrets.swift to $SECRETS_PATH"
