#!/bin/sh

# Xcode Cloud post-clone step.
#
# Secrets.swift is gitignored (it isn't in the repo), but the build depends on it.
# Regenerate it here from environment variables you set in the Xcode Cloud workflow:
#   SUPABASE_URL        e.g. https://<project>.supabase.co
#   SUPABASE_ANON_KEY   the anon/publishable key (public-by-design; RLS is the real defense)
#
# To set them: App Store Connect → Xcode Cloud → your workflow → Environment → Environment Variables.

set -e

if [ -z "$SUPABASE_URL" ] || [ -z "$SUPABASE_ANON_KEY" ]; then
  echo "❌ ci_post_clone: SUPABASE_URL and/or SUPABASE_ANON_KEY are not set."
  echo "   Set them in the Xcode Cloud workflow's Environment Variables, then re-run."
  exit 1
fi

SECRETS_PATH="$CI_PRIMARY_REPOSITORY_PATH/BumpSetCut/Core/Networking/Secrets.swift"

cat > "$SECRETS_PATH" <<EOF
// Secrets.swift — generated by ci_scripts/ci_post_clone.sh during Xcode Cloud builds.
// Local dev keeps its own gitignored copy; do not commit this file.

import Foundation

enum Secrets {
    static let supabaseURL = "$SUPABASE_URL"
    static let supabaseAnonKey = "$SUPABASE_ANON_KEY"
}
EOF

echo "✅ ci_post_clone: wrote Secrets.swift to $SECRETS_PATH"

# Validate the key BEFORE shipping it — a corrupted env var (e.g. a key pasted
# with embedded line breaks, which broke builds 35-37) otherwise produces a
# green build whose app can't reach the backend at all.
if [ "$(printf '%s' "$SUPABASE_ANON_KEY" | tr -d '[:space:]')" != "$SUPABASE_ANON_KEY" ]; then
  echo "❌ ci_post_clone: SUPABASE_ANON_KEY contains whitespace/line breaks."
  echo "   Re-paste it as one unbroken line in the Xcode Cloud workflow environment variables."
  exit 1
fi

HEALTH_STATUS=$(curl -s -o /dev/null -w "%{http_code}" --max-time 15 --retry 2 \
  "$SUPABASE_URL/auth/v1/health" -H "apikey: $SUPABASE_ANON_KEY" || true)
HEALTH_STATUS=${HEALTH_STATUS:-000}
if [ "$HEALTH_STATUS" != "200" ]; then
  echo "❌ ci_post_clone: Supabase auth health check failed (HTTP $HEALTH_STATUS)."
  echo "   SUPABASE_ANON_KEY is likely invalid or rotated — a build with a bad key ships an app that cannot sign in."
  exit 1
fi
echo "✅ ci_post_clone: Supabase key validated against $SUPABASE_URL (HTTP 200)"

# Stamp a unique, monotonically increasing build number so every Xcode Cloud
# build can be delivered to TestFlight without manual bumps. CI_BUILD_NUMBER
# is Xcode Cloud's own build counter (already > any manually uploaded build).
if [ -n "$CI_BUILD_NUMBER" ]; then
  cd "$CI_PRIMARY_REPOSITORY_PATH"
  agvtool new-version -all "$CI_BUILD_NUMBER"
  echo "✅ ci_post_clone: build number set to $CI_BUILD_NUMBER"
fi
